import type {
  InventoryItem,
  Loan,
  Maintenance,
  AuditLog,
  User,
  DashboardStats,
  LabMap,
} from "./types"

export const mockItems: InventoryItem[] = [
  {
    id: "1",
    internalCode: "LAB-FIS-EQ-001",
    patrimonyNumber: "USCS-2023-0001",
    name: "Osciloscópio Digital 100MHz",
    technicalDescription: "Osciloscópio digital de 2 canais, largura de banda 100MHz, taxa de amostragem 1GSa/s, tela LCD 7 polegadas, interface USB para transferência de dados.",
    category: "Equipamento de medição",
    brand: "Tektronix",
    model: "TBS1102C",
    serialNumber: "C012345",
    quantity: 1,
    unit: "Unidade",
    location: "Lab Física - Bancada 1",
    laboratory: "Laboratório de Física",
    responsible: "Prof. Dr. Carlos Silva",
    conservationState: "Ótimo",
    operatingCondition: "Funcionando",
    acquisitionDate: "2023-03-15",
    acquisitionValue: "R$ 4.500,00",
    usageStatus: "Em uso",
    maintenanceNeed: "Não",
    observations: "Equipamento calibrado em janeiro/2024",
    criticality: "Alta",
    lastMaintenance: "2024-01-15",
    nextMaintenance: "2025-01-15",
    linkedProject: "Projeto de extensão em instrumentação",
    fundingSource: "FAPESP",
    photos: [],
    createdAt: "2023-03-15T10:00:00Z",
    updatedAt: "2024-01-15T14:30:00Z",
  },
  {
    id: "2",
    internalCode: "LAB-FIS-EQ-002",
    patrimonyNumber: "USCS-2023-0002",
    name: "Multímetro Digital",
    technicalDescription: "Multímetro digital True-RMS, medição de tensão AC/DC até 1000V, corrente até 10A, resistência, capacitância e frequência.",
    category: "Equipamento de medição",
    brand: "Fluke",
    model: "117",
    serialNumber: "F789012",
    quantity: 5,
    unit: "Unidade",
    location: "Lab Física - Armário A",
    laboratory: "Laboratório de Física",
    responsible: "Técnico João Santos",
    conservationState: "Bom",
    operatingCondition: "Funcionando",
    acquisitionDate: "2022-08-20",
    acquisitionValue: "R$ 850,00",
    usageStatus: "Em uso",
    maintenanceNeed: "Não",
    observations: "",
    criticality: "Média",
    lastMaintenance: null,
    nextMaintenance: null,
    linkedProject: "Aula prática de circuitos",
    fundingSource: "Recurso próprio",
    photos: [],
    createdAt: "2022-08-20T09:00:00Z",
    updatedAt: "2022-08-20T09:00:00Z",
  },
  {
    id: "3",
    internalCode: "LAB-FIS-EQ-003",
    patrimonyNumber: "USCS-2022-0045",
    name: "Fonte de Alimentação DC",
    technicalDescription: "Fonte de alimentação DC regulável, 0-30V, 0-5A, display digital, proteção contra curto-circuito e sobrecarga.",
    category: "Equipamento de medição",
    brand: "Minipa",
    model: "MPL-3305M",
    serialNumber: "M456789",
    quantity: 8,
    unit: "Unidade",
    location: "Lab Física - Bancada 2",
    laboratory: "Laboratório de Física",
    responsible: "Prof. Dr. Carlos Silva",
    conservationState: "Regular",
    operatingCondition: "Funcionando parcialmente",
    acquisitionDate: "2020-05-10",
    acquisitionValue: "R$ 650,00",
    usageStatus: "Em manutenção",
    maintenanceNeed: "Sim",
    observations: "2 unidades com display danificado, aguardando peças",
    criticality: "Média",
    lastMaintenance: "2023-06-15",
    nextMaintenance: "2024-06-15",
    linkedProject: "",
    fundingSource: "Recurso próprio",
    photos: [],
    createdAt: "2020-05-10T11:00:00Z",
    updatedAt: "2023-11-20T16:45:00Z",
  },
  {
    id: "4",
    internalCode: "LAB-ROB-KIT-001",
    patrimonyNumber: "USCS-2024-0012",
    name: "Kit Arduino Educacional",
    technicalDescription: "Kit completo para ensino de robótica contendo Arduino UNO R3, protoboard, jumpers, LEDs, resistores, sensores diversos e manual didático.",
    category: "Kit didático",
    brand: "Arduino",
    model: "Starter Kit",
    serialNumber: "NÃO POSSUI",
    quantity: 15,
    unit: "Kit",
    location: "Lab Robótica - Armário B",
    laboratory: "Laboratório de Robótica",
    responsible: "Prof. Dra. Ana Martins",
    conservationState: "Ótimo",
    operatingCondition: "Funcionando",
    acquisitionDate: "2024-02-01",
    acquisitionValue: "R$ 350,00",
    usageStatus: "Em uso",
    maintenanceNeed: "Não",
    observations: "Kits novos para disciplina de Robótica I",
    criticality: "Alta",
    lastMaintenance: null,
    nextMaintenance: null,
    linkedProject: "Iniciação científica em robótica",
    fundingSource: "FINEP",
    photos: [],
    createdAt: "2024-02-01T08:00:00Z",
    updatedAt: "2024-02-01T08:00:00Z",
  },
  {
    id: "5",
    internalCode: "LAB-ROB-EQ-001",
    patrimonyNumber: "USCS-2023-0089",
    name: "ESP32 DevKit V1",
    technicalDescription: "Módulo de desenvolvimento ESP32 com WiFi e Bluetooth integrados, 30 pinos GPIO, programável via Arduino IDE.",
    category: "Equipamento de automação",
    brand: "Espressif",
    model: "ESP32-WROOM-32",
    serialNumber: "NÃO POSSUI",
    quantity: 20,
    unit: "Unidade",
    location: "Lab Robótica - Gaveta 3",
    laboratory: "Laboratório de Robótica",
    responsible: "Monitor Lucas Oliveira",
    conservationState: "Bom",
    operatingCondition: "Funcionando",
    acquisitionDate: "2023-08-15",
    acquisitionValue: "R$ 45,00",
    usageStatus: "Em uso",
    maintenanceNeed: "Não",
    observations: "3 unidades emprestadas para projeto de TCC",
    criticality: "Média",
    lastMaintenance: null,
    nextMaintenance: null,
    linkedProject: "Pesquisa em IoT",
    fundingSource: "Doação",
    photos: [],
    createdAt: "2023-08-15T14:00:00Z",
    updatedAt: "2024-03-10T11:20:00Z",
  },
  {
    id: "6",
    internalCode: "LAB-ROB-EQ-002",
    patrimonyNumber: "SEM PATRIMÔNIO",
    name: "Sensor Ultrassônico HC-SR04",
    technicalDescription: "Sensor de distância ultrassônico, alcance 2cm-400cm, frequência 40Hz, compatível com Arduino e ESP32.",
    category: "Equipamento de automação",
    brand: "GENÉRICO",
    model: "HC-SR04",
    serialNumber: "NÃO POSSUI",
    quantity: 30,
    unit: "Unidade",
    location: "Lab Robótica - Gaveta 4",
    laboratory: "Laboratório de Robótica",
    responsible: "Prof. Dra. Ana Martins",
    conservationState: "Bom",
    operatingCondition: "Funcionando",
    acquisitionDate: "2023-05-20",
    acquisitionValue: "R$ 15,00",
    usageStatus: "Em uso",
    maintenanceNeed: "Não",
    observations: "",
    criticality: "Baixa",
    lastMaintenance: null,
    nextMaintenance: null,
    linkedProject: "Aula prática de robótica",
    fundingSource: "Recurso próprio",
    photos: [],
    createdAt: "2023-05-20T10:00:00Z",
    updatedAt: "2023-05-20T10:00:00Z",
  },
  {
    id: "7",
    internalCode: "LAB-ROB-EQ-003",
    patrimonyNumber: "USCS-2022-0156",
    name: "Servo Motor MG996R",
    technicalDescription: "Servo motor de alto torque, engrenagem metálica, torque 11kg/cm, rotação 180°, alimentação 4.8-7.2V.",
    category: "Equipamento de robótica",
    brand: "TowerPro",
    model: "MG996R",
    serialNumber: "NÃO POSSUI",
    quantity: 25,
    unit: "Unidade",
    location: "Lab Robótica - Armário A",
    laboratory: "Laboratório de Robótica",
    responsible: "Técnico Pedro Alves",
    conservationState: "Bom",
    operatingCondition: "Funcionando",
    acquisitionDate: "2022-11-10",
    acquisitionValue: "R$ 35,00",
    usageStatus: "Em uso",
    maintenanceNeed: "Não",
    observations: "5 unidades com folga no eixo - avaliar substituição",
    criticality: "Média",
    lastMaintenance: null,
    nextMaintenance: null,
    linkedProject: "Projeto braço robótico",
    fundingSource: "CAPES",
    photos: [],
    createdAt: "2022-11-10T09:30:00Z",
    updatedAt: "2024-02-28T15:00:00Z",
  },
  {
    id: "8",
    internalCode: "LAB-FAB-IMP3D-001",
    patrimonyNumber: "USCS-2023-0201",
    name: "Impressora 3D FDM",
    technicalDescription: "Impressora 3D de filamento, volume de impressão 220x220x250mm, resolução 0.1mm, compatível com PLA, ABS, PETG.",
    category: "Equipamento de fabricação digital",
    brand: "Creality",
    model: "Ender 3 V2",
    serialNumber: "CR3V2-2023-0456",
    quantity: 2,
    unit: "Unidade",
    location: "Lab Robótica - Mesa de Impressão",
    laboratory: "Laboratório de Robótica",
    responsible: "Prof. Dra. Ana Martins",
    conservationState: "Bom",
    operatingCondition: "Funcionando",
    acquisitionDate: "2023-06-01",
    acquisitionValue: "R$ 1.800,00",
    usageStatus: "Em uso",
    maintenanceNeed: "Avaliar",
    observations: "Verificar nivelamento da mesa antes de cada impressão",
    criticality: "Alta",
    lastMaintenance: "2024-01-20",
    nextMaintenance: "2024-04-20",
    linkedProject: "Fab Lab universitário",
    fundingSource: "Convênio",
    photos: [],
    createdAt: "2023-06-01T13:00:00Z",
    updatedAt: "2024-01-20T10:15:00Z",
  },
  {
    id: "9",
    internalCode: "LAB-FIS-FER-001",
    patrimonyNumber: "USCS-2021-0078",
    name: "Alicate Amperímetro",
    technicalDescription: "Alicate amperímetro digital, medição de corrente AC até 400A, tensão AC/DC até 600V, True-RMS.",
    category: "Ferramenta técnica",
    brand: "Hikari",
    model: "HA-3200",
    serialNumber: "HK2021789",
    quantity: 3,
    unit: "Unidade",
    location: "Lab Física - Armário de Ferramentas",
    laboratory: "Laboratório de Física",
    responsible: "Técnico João Santos",
    conservationState: "Regular",
    operatingCondition: "Funcionando",
    acquisitionDate: "2021-03-25",
    acquisitionValue: "R$ 280,00",
    usageStatus: "Em uso",
    maintenanceNeed: "Sim",
    observations: "1 unidade precisa trocar bateria",
    criticality: "Média",
    lastMaintenance: "2023-03-25",
    nextMaintenance: "2025-03-25",
    linkedProject: "",
    fundingSource: "Recurso próprio",
    photos: [],
    createdAt: "2021-03-25T11:30:00Z",
    updatedAt: "2024-02-10T09:00:00Z",
  },
  {
    id: "10",
    internalCode: "LAB-ROB-MOB-001",
    patrimonyNumber: "USCS-2020-0234",
    name: "Bancada Eletrônica",
    technicalDescription: "Bancada para trabalho eletrônico com tampo antiestático, iluminação LED, tomadas 110/220V e suporte para ferramentas.",
    category: "Mobiliário técnico",
    brand: "Marcon",
    model: "BE-150",
    serialNumber: "MB2020-0234",
    quantity: 6,
    unit: "Unidade",
    location: "Lab Robótica - Área de Montagem",
    laboratory: "Laboratório de Robótica",
    responsible: "Coordenação Engenharia",
    conservationState: "Bom",
    operatingCondition: "Funcionando",
    acquisitionDate: "2020-02-15",
    acquisitionValue: "R$ 2.500,00",
    usageStatus: "Em uso",
    maintenanceNeed: "Não",
    observations: "",
    criticality: "Baixa",
    lastMaintenance: null,
    nextMaintenance: null,
    linkedProject: "",
    fundingSource: "Recurso próprio",
    photos: [],
    createdAt: "2020-02-15T08:00:00Z",
    updatedAt: "2020-02-15T08:00:00Z",
  },
  {
    id: "11",
    internalCode: "LAB-FIS-EQ-004",
    patrimonyNumber: "EM REGULARIZAÇÃO",
    name: "Gerador de Funções",
    technicalDescription: "Gerador de funções digital, 1Hz-25MHz, ondas senoidal, quadrada, triangular e rampa, display LCD.",
    category: "Equipamento de medição",
    brand: "Minipa",
    model: "MFG-4225",
    serialNumber: "MFG2022001",
    quantity: 2,
    unit: "Unidade",
    location: "Lab Física - Bancada 3",
    laboratory: "Laboratório de Física",
    responsible: "Prof. Dr. Carlos Silva",
    conservationState: "Ótimo",
    operatingCondition: "Funcionando",
    acquisitionDate: "DESCONHECIDA",
    acquisitionValue: "NÃO INFORMADO",
    usageStatus: "Em uso",
    maintenanceNeed: "Não",
    observations: "Equipamento doado, aguardando tombamento patrimonial",
    criticality: "Alta",
    lastMaintenance: null,
    nextMaintenance: null,
    linkedProject: "Projeto de extensão em instrumentação",
    fundingSource: "Doação",
    photos: [],
    createdAt: "2024-01-10T14:00:00Z",
    updatedAt: "2024-03-05T16:30:00Z",
  },
  {
    id: "12",
    internalCode: "LAB-ROB-CLP-001",
    patrimonyNumber: "USCS-2023-0178",
    name: "CLP Didático",
    technicalDescription: "Controlador Lógico Programável didático com 8 entradas digitais, 6 saídas a relé, comunicação serial e software de programação.",
    category: "Equipamento de automação",
    brand: "Siemens",
    model: "LOGO! 8",
    serialNumber: "SL8-2023-789",
    quantity: 4,
    unit: "Unidade",
    location: "Lab Robótica - Bancada de Automação",
    laboratory: "Laboratório de Robótica",
    responsible: "Prof. Dra. Ana Martins",
    conservationState: "Ótimo",
    operatingCondition: "Funcionando",
    acquisitionDate: "2023-09-01",
    acquisitionValue: "R$ 1.200,00",
    usageStatus: "Em uso",
    maintenanceNeed: "Não",
    observations: "Utilizados na disciplina de Automação Industrial",
    criticality: "Crítica",
    lastMaintenance: null,
    nextMaintenance: null,
    linkedProject: "Pesquisa em automação industrial",
    fundingSource: "FINEP",
    photos: [],
    createdAt: "2023-09-01T09:00:00Z",
    updatedAt: "2023-09-01T09:00:00Z",
  },
  {
    id: "13",
    internalCode: "LAB-FIS-EPI-001",
    patrimonyNumber: "SEM PATRIMÔNIO",
    name: "Óculos de Proteção",
    technicalDescription: "Óculos de segurança com proteção lateral, lente incolor antiembaçante, armação em policarbonato.",
    category: "EPI",
    brand: "Vonder",
    model: "Evolution",
    serialNumber: "NÃO POSSUI",
    quantity: 30,
    unit: "Unidade",
    location: "Lab Física - Armário de EPI",
    laboratory: "Laboratório de Física",
    responsible: "Técnico João Santos",
    conservationState: "Bom",
    operatingCondition: "Funcionando",
    acquisitionDate: "2024-01-05",
    acquisitionValue: "R$ 12,00",
    usageStatus: "Em uso",
    maintenanceNeed: "Não",
    observations: "Reposição semestral programada",
    criticality: "Baixa",
    lastMaintenance: null,
    nextMaintenance: null,
    linkedProject: "",
    fundingSource: "Recurso próprio",
    photos: [],
    createdAt: "2024-01-05T10:00:00Z",
    updatedAt: "2024-01-05T10:00:00Z",
  },
  {
    id: "14",
    internalCode: "LAB-ROB-EQ-004",
    patrimonyNumber: "USCS-2022-0089",
    name: "Motor DC 12V",
    technicalDescription: "Motor DC 12V com redução, torque 5kg.cm, rotação 100RPM, eixo duplo, ideal para projetos de robótica móvel.",
    category: "Equipamento de robótica",
    brand: "GENÉRICO",
    model: "JGB37-520",
    serialNumber: "NÃO POSSUI",
    quantity: 16,
    unit: "Unidade",
    location: "Lab Robótica - Gaveta 5",
    laboratory: "Laboratório de Robótica",
    responsible: "Monitor Lucas Oliveira",
    conservationState: "Bom",
    operatingCondition: "Funcionando",
    acquisitionDate: "2022-07-20",
    acquisitionValue: "R$ 55,00",
    usageStatus: "Em uso",
    maintenanceNeed: "Não",
    observations: "4 unidades reservadas para competição de robótica",
    criticality: "Média",
    lastMaintenance: null,
    nextMaintenance: null,
    linkedProject: "Competição de robótica universitária",
    fundingSource: "Recurso próprio",
    photos: [],
    createdAt: "2022-07-20T15:00:00Z",
    updatedAt: "2024-03-01T11:00:00Z",
  },
  {
    id: "15",
    internalCode: "LAB-FIS-EQ-005",
    patrimonyNumber: "USCS-2019-0156",
    name: "Protoboard 830 Pontos",
    technicalDescription: "Placa de prototipagem sem solda, 830 pontos de contato, barras de alimentação laterais, base adesiva.",
    category: "Ferramenta técnica",
    brand: "Akiyama",
    model: "MB-102",
    serialNumber: "NÃO POSSUI",
    quantity: 40,
    unit: "Unidade",
    location: "Lab Física - Armário B",
    laboratory: "Laboratório de Física",
    responsible: "Técnico João Santos",
    conservationState: "Regular",
    operatingCondition: "Funcionando",
    acquisitionDate: "2019-03-10",
    acquisitionValue: "R$ 18,00",
    usageStatus: "Em uso",
    maintenanceNeed: "Avaliar",
    observations: "Algumas unidades com trilhas desgastadas",
    criticality: "Baixa",
    lastMaintenance: null,
    nextMaintenance: null,
    linkedProject: "Aula prática de circuitos",
    fundingSource: "Recurso próprio",
    photos: [],
    createdAt: "2019-03-10T08:30:00Z",
    updatedAt: "2024-02-15T14:00:00Z",
  },
  {
    id: "16",
    internalCode: "LAB-ROB-EQ-005",
    patrimonyNumber: "USCS-2024-0025",
    name: "Raspberry Pi 4 Model B",
    technicalDescription: "Computador de placa única, processador quad-core 1.5GHz, 4GB RAM, WiFi, Bluetooth, 2x micro HDMI, USB-C.",
    category: "Equipamento de informática",
    brand: "Raspberry Pi Foundation",
    model: "Pi 4 Model B 4GB",
    serialNumber: "RPI4-2024-001",
    quantity: 5,
    unit: "Unidade",
    location: "Lab Robótica - Armário de Computação",
    laboratory: "Laboratório de Robótica",
    responsible: "Prof. Dra. Ana Martins",
    conservationState: "Ótimo",
    operatingCondition: "Funcionando",
    acquisitionDate: "2024-01-15",
    acquisitionValue: "R$ 580,00",
    usageStatus: "Em uso",
    maintenanceNeed: "Não",
    observations: "Utilizados em projetos de visão computacional",
    criticality: "Alta",
    lastMaintenance: null,
    nextMaintenance: null,
    linkedProject: "Pesquisa em visão computacional",
    fundingSource: "FAPESP",
    photos: [],
    createdAt: "2024-01-15T11:00:00Z",
    updatedAt: "2024-01-15T11:00:00Z",
  },
]

export const mockLoans: Loan[] = [
  {
    id: "1",
    itemId: "5",
    itemCode: "LAB-ROB-EQ-001",
    itemName: "ESP32 DevKit V1",
    requesterName: "Maria Fernandes",
    userType: "Aluno",
    identification: "RA: 2021.1.0456",
    quantityBorrowed: 3,
    originLab: "Laboratório de Robótica",
    purpose: "Desenvolvimento de TCC - Sistema IoT para agricultura",
    withdrawalDate: "2024-03-01",
    expectedReturnDate: "2024-04-15",
    actualReturnDate: null,
    deliveryResponsible: "Monitor Lucas Oliveira",
    receivingResponsible: null,
    observations: "Projeto orientado pela Prof. Dra. Ana Martins",
    status: "Ativo",
    createdAt: "2024-03-01T10:00:00Z",
  },
  {
    id: "2",
    itemId: "4",
    itemCode: "LAB-ROB-KIT-001",
    itemName: "Kit Arduino Educacional",
    requesterName: "Prof. Roberto Lima",
    userType: "Professor",
    identification: "Matrícula: P-2018-045",
    quantityBorrowed: 5,
    originLab: "Laboratório de Robótica",
    purpose: "Workshop de introdução à programação - Semana de Engenharia",
    withdrawalDate: "2024-02-20",
    expectedReturnDate: "2024-02-25",
    actualReturnDate: null,
    deliveryResponsible: "Técnico Pedro Alves",
    receivingResponsible: null,
    observations: "",
    status: "Atrasado",
    createdAt: "2024-02-20T14:00:00Z",
  },
  {
    id: "3",
    itemId: "2",
    itemCode: "LAB-FIS-EQ-002",
    itemName: "Multímetro Digital",
    requesterName: "Carlos Mendes",
    userType: "Monitor",
    identification: "Monitor Lab. Física",
    quantityBorrowed: 2,
    originLab: "Laboratório de Física",
    purpose: "Aula prática de medições elétricas - Turma EE-2024/1",
    withdrawalDate: "2024-03-10",
    expectedReturnDate: "2024-03-10",
    actualReturnDate: "2024-03-10",
    deliveryResponsible: "Técnico João Santos",
    receivingResponsible: "Técnico João Santos",
    observations: "Devolvidos em perfeito estado",
    status: "Devolvido",
    createdAt: "2024-03-10T08:00:00Z",
  },
  {
    id: "4",
    itemId: "8",
    itemCode: "LAB-FAB-IMP3D-001",
    itemName: "Impressora 3D FDM",
    requesterName: "Grupo de Pesquisa em Bioengenharia",
    userType: "Professor",
    identification: "Coord.: Prof. Dr. André Costa",
    quantityBorrowed: 1,
    originLab: "Laboratório de Robótica",
    purpose: "Impressão de protótipos de próteses ortopédicas",
    withdrawalDate: "2024-03-05",
    expectedReturnDate: "2024-03-20",
    actualReturnDate: null,
    deliveryResponsible: "Prof. Dra. Ana Martins",
    receivingResponsible: null,
    observations: "Impressora realocada temporariamente para Lab. Bioengenharia",
    status: "Ativo",
    createdAt: "2024-03-05T09:30:00Z",
  },
]

export const mockMaintenances: Maintenance[] = [
  {
    id: "1",
    itemId: "3",
    itemCode: "LAB-FIS-EQ-003",
    itemName: "Fonte de Alimentação DC",
    category: "Equipamento de medição",
    reportedProblem: "Display de 2 unidades apresentando falhas intermitentes, dificultando leitura de valores",
    maintenanceType: "Corretiva",
    responsible: "Técnico João Santos",
    supplierOrTechnician: "Assistência Técnica Minipa",
    openingDate: "2024-02-15",
    lastMaintenance: "2023-06-15",
    nextMaintenance: null,
    estimatedCost: "R$ 350,00",
    status: "Aguardando peça",
    criticality: "Média",
    observations: "Orçamento aprovado, aguardando chegada dos displays de reposição",
    createdAt: "2024-02-15T11:00:00Z",
    completedAt: null,
  },
  {
    id: "2",
    itemId: "8",
    itemCode: "LAB-FAB-IMP3D-001",
    itemName: "Impressora 3D FDM",
    category: "Equipamento de fabricação digital",
    reportedProblem: "Nivelamento automático da mesa com desvio, causando falhas na primeira camada",
    maintenanceType: "Preventiva",
    responsible: "Monitor Lucas Oliveira",
    supplierOrTechnician: "Manutenção interna",
    openingDate: "2024-03-01",
    lastMaintenance: "2024-01-20",
    nextMaintenance: "2024-04-20",
    estimatedCost: "R$ 0,00",
    status: "Concluída",
    criticality: "Alta",
    observations: "Realizado ajuste fino do sensor BLTouch e calibração da mesa",
    createdAt: "2024-03-01T10:00:00Z",
    completedAt: "2024-03-01T14:30:00Z",
  },
  {
    id: "3",
    itemId: "1",
    itemCode: "LAB-FIS-EQ-001",
    itemName: "Osciloscópio Digital 100MHz",
    category: "Equipamento de medição",
    reportedProblem: "Calibração anual programada",
    maintenanceType: "Calibração",
    responsible: "Prof. Dr. Carlos Silva",
    supplierOrTechnician: "Inmetro",
    openingDate: "2024-01-10",
    lastMaintenance: "2023-01-15",
    nextMaintenance: "2025-01-15",
    estimatedCost: "R$ 450,00",
    status: "Concluída",
    criticality: "Alta",
    observations: "Certificado de calibração arquivado. Equipamento dentro das especificações.",
    createdAt: "2024-01-10T08:00:00Z",
    completedAt: "2024-01-15T16:00:00Z",
  },
  {
    id: "4",
    itemId: "9",
    itemCode: "LAB-FIS-FER-001",
    itemName: "Alicate Amperímetro",
    category: "Ferramenta técnica",
    reportedProblem: "Bateria de 1 unidade descarregada, necessita substituição",
    maintenanceType: "Corretiva",
    responsible: "Técnico João Santos",
    supplierOrTechnician: "Manutenção interna",
    openingDate: "2024-03-08",
    lastMaintenance: "2023-03-25",
    nextMaintenance: "2025-03-25",
    estimatedCost: "R$ 25,00",
    status: "Aberta",
    criticality: "Baixa",
    observations: "Bateria 9V padrão, disponível no almoxarifado",
    createdAt: "2024-03-08T15:00:00Z",
    completedAt: null,
  },
  {
    id: "5",
    itemId: "12",
    itemCode: "LAB-ROB-CLP-001",
    itemName: "CLP Didático",
    category: "Equipamento de automação",
    reportedProblem: "Inspeção semestral de funcionamento das entradas e saídas",
    maintenanceType: "Inspeção",
    responsible: "Prof. Dra. Ana Martins",
    supplierOrTechnician: "Manutenção interna",
    openingDate: "2024-03-12",
    lastMaintenance: null,
    nextMaintenance: "2024-09-12",
    estimatedCost: "R$ 0,00",
    status: "Em andamento",
    criticality: "Crítica",
    observations: "Verificação de todas as 4 unidades antes do início do semestre",
    createdAt: "2024-03-12T09:00:00Z",
    completedAt: null,
  },
]

export const mockAuditLogs: AuditLog[] = [
  {
    id: "1",
    timestamp: "2024-03-12T14:30:00Z",
    userId: "1",
    userName: "Admin Sistema",
    action: "Criação",
    itemId: "16",
    itemCode: "LAB-ROB-EQ-005",
    laboratory: "Laboratório de Robótica",
    details: "Cadastro de 5 unidades de Raspberry Pi 4 Model B",
  },
  {
    id: "2",
    timestamp: "2024-03-10T11:20:00Z",
    userId: "2",
    userName: "Monitor Lucas Oliveira",
    action: "Empréstimo",
    itemId: "5",
    itemCode: "LAB-ROB-EQ-001",
    laboratory: "Laboratório de Robótica",
    details: "Empréstimo de 3 unidades de ESP32 DevKit para Maria Fernandes (TCC)",
  },
  {
    id: "3",
    timestamp: "2024-03-08T15:00:00Z",
    userId: "3",
    userName: "Técnico João Santos",
    action: "Manutenção",
    itemId: "9",
    itemCode: "LAB-FIS-FER-001",
    laboratory: "Laboratório de Física",
    details: "Abertura de ordem de manutenção para troca de bateria do alicate amperímetro",
  },
  {
    id: "4",
    timestamp: "2024-03-05T16:30:00Z",
    userId: "1",
    userName: "Admin Sistema",
    action: "Edição",
    itemId: "11",
    itemCode: "LAB-FIS-EQ-004",
    laboratory: "Laboratório de Física",
    details: "Atualização do status patrimonial para 'EM REGULARIZAÇÃO'",
  },
  {
    id: "5",
    timestamp: "2024-03-01T14:30:00Z",
    userId: "2",
    userName: "Monitor Lucas Oliveira",
    action: "Manutenção",
    itemId: "8",
    itemCode: "LAB-FAB-IMP3D-001",
    laboratory: "Laboratório de Robótica",
    details: "Conclusão de manutenção preventiva - calibração da mesa de impressão",
  },
  {
    id: "6",
    timestamp: "2024-02-28T15:00:00Z",
    userId: "4",
    userName: "Técnico Pedro Alves",
    action: "Alteração de estado",
    itemId: "7",
    itemCode: "LAB-ROB-EQ-003",
    laboratory: "Laboratório de Robótica",
    details: "Estado de conservação alterado para 'Bom' - 5 unidades com folga no eixo",
  },
  {
    id: "7",
    timestamp: "2024-02-20T14:00:00Z",
    userId: "4",
    userName: "Técnico Pedro Alves",
    action: "Empréstimo",
    itemId: "4",
    itemCode: "LAB-ROB-KIT-001",
    laboratory: "Laboratório de Robótica",
    details: "Empréstimo de 5 Kits Arduino para Prof. Roberto Lima - Workshop Semana de Engenharia",
  },
  {
    id: "8",
    timestamp: "2024-02-15T14:00:00Z",
    userId: "5",
    userName: "Prof. Dr. Carlos Silva",
    action: "Edição",
    itemId: "15",
    itemCode: "LAB-FIS-EQ-005",
    laboratory: "Laboratório de Física",
    details: "Observação adicionada: algumas protoboards com trilhas desgastadas",
  },
  {
    id: "9",
    timestamp: "2024-02-15T11:00:00Z",
    userId: "3",
    userName: "Técnico João Santos",
    action: "Manutenção",
    itemId: "3",
    itemCode: "LAB-FIS-EQ-003",
    laboratory: "Laboratório de Física",
    details: "Abertura de ordem de manutenção corretiva - display com falhas",
  },
  {
    id: "10",
    timestamp: "2024-01-15T14:30:00Z",
    userId: "5",
    userName: "Prof. Dr. Carlos Silva",
    action: "Manutenção",
    itemId: "1",
    itemCode: "LAB-FIS-EQ-001",
    laboratory: "Laboratório de Física",
    details: "Conclusão de calibração anual do osciloscópio - certificado Inmetro arquivado",
  },
]

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Administrador do Sistema",
    email: "admin@uscs.edu.br",
    role: "Administrador",
    linkedLaboratory: "Todos",
    status: "Ativo",
    lastAccess: "2024-03-12T14:30:00Z",
    createdAt: "2020-01-01T00:00:00Z",
  },
  {
    id: "2",
    name: "Lucas Oliveira",
    email: "lucas.oliveira@uscs.edu.br",
    role: "Monitor",
    linkedLaboratory: "Laboratório de Robótica",
    status: "Ativo",
    lastAccess: "2024-03-12T11:20:00Z",
    createdAt: "2023-02-15T10:00:00Z",
  },
  {
    id: "3",
    name: "João Santos",
    email: "joao.santos@uscs.edu.br",
    role: "Técnico/Laboratorista",
    linkedLaboratory: "Laboratório de Física",
    status: "Ativo",
    lastAccess: "2024-03-12T08:00:00Z",
    createdAt: "2019-08-01T08:00:00Z",
  },
  {
    id: "4",
    name: "Pedro Alves",
    email: "pedro.alves@uscs.edu.br",
    role: "Técnico/Laboratorista",
    linkedLaboratory: "Laboratório de Robótica",
    status: "Ativo",
    lastAccess: "2024-03-11T16:45:00Z",
    createdAt: "2021-03-10T09:00:00Z",
  },
  {
    id: "5",
    name: "Prof. Dr. Carlos Silva",
    email: "carlos.silva@uscs.edu.br",
    role: "Professor",
    linkedLaboratory: "Laboratório de Física",
    status: "Ativo",
    lastAccess: "2024-03-10T17:30:00Z",
    createdAt: "2015-02-01T08:00:00Z",
  },
  {
    id: "6",
    name: "Prof. Dra. Ana Martins",
    email: "ana.martins@uscs.edu.br",
    role: "Professor",
    linkedLaboratory: "Laboratório de Robótica",
    status: "Ativo",
    lastAccess: "2024-03-12T10:15:00Z",
    createdAt: "2018-08-15T08:00:00Z",
  },
  {
    id: "7",
    name: "Visitante Auditoria",
    email: "auditoria@uscs.edu.br",
    role: "Visualizador",
    linkedLaboratory: "Todos",
    status: "Inativo",
    lastAccess: "2024-01-30T14:00:00Z",
    createdAt: "2024-01-15T10:00:00Z",
  },
]

export const mockDashboardStats: DashboardStats = {
  totalItems: 16,
  inUse: 12,
  inReserve: 1,
  borrowed: 2,
  inMaintenance: 1,
  inCalibration: 0,
  deactivated: 0,
  forDisposal: 0,
  highCriticality: 5,
  upcomingMaintenance: 3,
  withoutPatrimony: 2,
  recentMovements: 10,
}

export function getItemsByLaboratory(laboratory: string): InventoryItem[] {
  return mockItems.filter((item) => item.laboratory === laboratory)
}

export const mockLabMaps: LabMap[] = [
  {
    id: "map-robotica",
    laboratory: "Laboratório de Robótica",
    name: "Planta - Lab. Robótica",
    width: 1000,
    height: 700,
    elements: [
      // Walls
      { id: "w1", type: "wall", x: 50, y: 50, width: 900, height: 10, rotation: 0, label: "Parede Norte" },
      { id: "w2", type: "wall", x: 50, y: 50, width: 10, height: 600, rotation: 0, label: "Parede Oeste" },
      { id: "w3", type: "wall", x: 50, y: 640, width: 900, height: 10, rotation: 0, label: "Parede Sul" },
      { id: "w4", type: "wall", x: 940, y: 50, width: 10, height: 600, rotation: 0, label: "Parede Leste" },
      // Door
      { id: "d1", type: "door", x: 880, y: 640, width: 60, height: 10, rotation: 0, label: "Porta Principal" },
      // Windows
      { id: "win1", type: "window", x: 200, y: 50, width: 120, height: 10, rotation: 0, label: "Janela 1" },
      { id: "win2", type: "window", x: 400, y: 50, width: 120, height: 10, rotation: 0, label: "Janela 2" },
      { id: "win3", type: "window", x: 600, y: 50, width: 120, height: 10, rotation: 0, label: "Janela 3" },
      // Tables (based on photos - large white tables with blue stools)
      { id: "t1", type: "table", x: 120, y: 150, width: 200, height: 120, rotation: 0, label: "Bancada 1" },
      { id: "t2", type: "table", x: 400, y: 150, width: 200, height: 120, rotation: 0, label: "Bancada 2" },
      { id: "t3", type: "table", x: 680, y: 150, width: 200, height: 120, rotation: 0, label: "Bancada 3" },
      { id: "t4", type: "table", x: 120, y: 400, width: 200, height: 120, rotation: 0, label: "Bancada de Automação" },
      { id: "t5", type: "table", x: 400, y: 400, width: 200, height: 120, rotation: 0, label: "Mesa de Impressão" },
      // Chairs (stools around tables)
      { id: "ch1", type: "chair", x: 140, y: 130, width: 20, height: 20, rotation: 0 },
      { id: "ch2", type: "chair", x: 200, y: 130, width: 20, height: 20, rotation: 0 },
      { id: "ch3", type: "chair", x: 260, y: 130, width: 20, height: 20, rotation: 0 },
      { id: "ch4", type: "chair", x: 140, y: 280, width: 20, height: 20, rotation: 0 },
      { id: "ch5", type: "chair", x: 200, y: 280, width: 20, height: 20, rotation: 0 },
      { id: "ch6", type: "chair", x: 260, y: 280, width: 20, height: 20, rotation: 0 },
      { id: "ch7", type: "chair", x: 420, y: 130, width: 20, height: 20, rotation: 0 },
      { id: "ch8", type: "chair", x: 480, y: 130, width: 20, height: 20, rotation: 0 },
      { id: "ch9", type: "chair", x: 540, y: 130, width: 20, height: 20, rotation: 0 },
      // Cabinets
      { id: "cab1", type: "cabinet", x: 70, y: 70, width: 40, height: 80, rotation: 0, label: "Armário A" },
      { id: "cab2", type: "cabinet", x: 70, y: 300, width: 40, height: 80, rotation: 0, label: "Armário B" },
      { id: "cab3", type: "cabinet", x: 70, y: 530, width: 40, height: 80, rotation: 0, label: "Armário de Computação" },
      // Electrical panel
      { id: "ep1", type: "electrical-panel", x: 70, y: 180, width: 30, height: 100, rotation: 0, label: "Painel Elétrico" },
      // Equipment markers (linked to inventory items)
      { id: "eq1", type: "equipment", x: 160, y: 180, width: 30, height: 30, rotation: 0, label: "Kit Arduino", linkedItemId: "4" },
      { id: "eq2", type: "equipment", x: 440, y: 180, width: 30, height: 30, rotation: 0, label: "ESP32 DevKit", linkedItemId: "5" },
      { id: "eq3", type: "equipment", x: 720, y: 180, width: 30, height: 30, rotation: 0, label: "Servo Motor", linkedItemId: "7" },
      { id: "eq4", type: "equipment", x: 460, y: 430, width: 30, height: 30, rotation: 0, label: "Impressora 3D", linkedItemId: "8" },
      { id: "eq5", type: "equipment", x: 160, y: 430, width: 30, height: 30, rotation: 0, label: "CLP Didático", linkedItemId: "12" },
      { id: "eq6", type: "equipment", x: 500, y: 180, width: 30, height: 30, rotation: 0, label: "Sensor HC-SR04", linkedItemId: "6" },
      { id: "eq7", type: "equipment", x: 90, y: 550, width: 30, height: 30, rotation: 0, label: "Raspberry Pi 4", linkedItemId: "16" },
      // Labels
      { id: "lbl1", type: "label", x: 680, y: 580, width: 200, height: 40, rotation: 0, label: "Lousa" },
    ],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-03-10T10:00:00Z",
  },
  {
    id: "map-fisica",
    laboratory: "Laboratório de Física",
    name: "Planta - Lab. Física",
    width: 900,
    height: 600,
    elements: [
      // Walls
      { id: "w1", type: "wall", x: 50, y: 50, width: 800, height: 10, rotation: 0 },
      { id: "w2", type: "wall", x: 50, y: 50, width: 10, height: 500, rotation: 0 },
      { id: "w3", type: "wall", x: 50, y: 540, width: 800, height: 10, rotation: 0 },
      { id: "w4", type: "wall", x: 840, y: 50, width: 10, height: 500, rotation: 0 },
      // Door
      { id: "d1", type: "door", x: 780, y: 540, width: 60, height: 10, rotation: 0, label: "Porta" },
      // Windows
      { id: "win1", type: "window", x: 150, y: 50, width: 100, height: 10, rotation: 0 },
      { id: "win2", type: "window", x: 350, y: 50, width: 100, height: 10, rotation: 0 },
      { id: "win3", type: "window", x: 550, y: 50, width: 100, height: 10, rotation: 0 },
      // Tables
      { id: "t1", type: "table", x: 120, y: 120, width: 180, height: 100, rotation: 0, label: "Bancada 1" },
      { id: "t2", type: "table", x: 370, y: 120, width: 180, height: 100, rotation: 0, label: "Bancada 2" },
      { id: "t3", type: "table", x: 620, y: 120, width: 180, height: 100, rotation: 0, label: "Bancada 3" },
      { id: "t4", type: "table", x: 120, y: 350, width: 180, height: 100, rotation: 0, label: "Bancada 4" },
      // Cabinets
      { id: "cab1", type: "cabinet", x: 70, y: 70, width: 40, height: 70, rotation: 0, label: "Armário A" },
      { id: "cab2", type: "cabinet", x: 70, y: 250, width: 40, height: 70, rotation: 0, label: "Armário B" },
      { id: "cab3", type: "cabinet", x: 70, y: 450, width: 40, height: 70, rotation: 0, label: "Armário de EPI" },
      { id: "cab4", type: "cabinet", x: 70, y: 350, width: 40, height: 70, rotation: 0, label: "Armário de Ferramentas" },
      // Equipment markers
      { id: "eq1", type: "equipment", x: 160, y: 140, width: 30, height: 30, rotation: 0, label: "Osciloscópio", linkedItemId: "1" },
      { id: "eq2", type: "equipment", x: 410, y: 140, width: 30, height: 30, rotation: 0, label: "Multímetro", linkedItemId: "2" },
      { id: "eq3", type: "equipment", x: 660, y: 140, width: 30, height: 30, rotation: 0, label: "Gerador de Funções", linkedItemId: "11" },
      { id: "eq4", type: "equipment", x: 160, y: 370, width: 30, height: 30, rotation: 0, label: "Fonte DC", linkedItemId: "3" },
      { id: "eq5", type: "equipment", x: 90, y: 270, width: 30, height: 30, rotation: 0, label: "Protoboard", linkedItemId: "15" },
      { id: "eq6", type: "equipment", x: 90, y: 470, width: 30, height: 30, rotation: 0, label: "Óculos Proteção", linkedItemId: "13" },
      { id: "eq7", type: "equipment", x: 90, y: 370, width: 30, height: 30, rotation: 0, label: "Alicate Amperím.", linkedItemId: "9" },
    ],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-03-10T10:00:00Z",
  },
]

export function getItemById(id: string): InventoryItem | undefined {
  return mockItems.find((item) => item.id === id)
}

export function getLoansByStatus(status: string): Loan[] {
  return mockLoans.filter((loan) => loan.status === status)
}

export function getMaintenancesByStatus(status: string): Maintenance[] {
  return mockMaintenances.filter((m) => m.status === status)
}

export function getAuditLogsByItem(itemId: string): AuditLog[] {
  return mockAuditLogs.filter((log) => log.itemId === itemId)
}

export function getLabMap(laboratory: string): LabMap | undefined {
  return mockLabMaps.find((m) => m.laboratory === laboratory)
}
